name: avaca_server
description: Windows-only AVACA Server application.
publish_to: none
version: 0.10.3+2051

environment:
  sdk: ^3.11.5
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  avaca_domain:
    path: ../../packages/avaca_domain
  avaca_library:
    path: ../../packages/avaca_library
  avaca_protocol:
    path: ../../packages/avaca_protocol
  avaca_remote_core:
    path: ../../packages/avaca_remote_core
  avaca_scraper:
    path: ../../packages/avaca_scraper
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
