name: avaca_protocol
description: Versioned AVACA Server to AVACA wire contract.
publish_to: none

environment:
  sdk: ^3.11.5

dependencies:
  crypto: ^3.0.7
  avaca_domain:
    path: ../avaca_domain

dev_dependencies:
  test: ^1.26.3
