name: avaca_client_app
description: AVACA browsing and playback client application.
publish_to: none
version: 0.10.4+2052

environment:
  sdk: ^3.11.5
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  avaca_client:
    path: ../../packages/avaca_client
  avaca_domain:
    path: ../../packages/avaca_domain
  avaca_player_native:
    path: ../../packages/avaca_player_native
  avaca_protocol:
    path: ../../packages/avaca_protocol
  avaca_remote_core:
    path: ../../packages/avaca_remote_core
  mobile_scanner: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
